
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nstdmvzaiuecsluhgdcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zdGRtdnphaXVlY3NsdWhnZGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTE4OTIsImV4cCI6MjA1NjM4Nzg5Mn0.2Yt6QwZpud0sZ85faIfHMrGO50t0ugbucto_kRtqPOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
